### ISSUE TITLE
install unsucessful

### ISSUE THREAD

**Issue by Ram9090** [spazziale/pokemmo-flatpak-manifest#5]
Hi , I have just bought a steam deck , i saw your post in the forums , i have been trying to run the flatpack on the steam deck for the past 2 weeks , can you please guide me iam so confused , i have installed the flatpack and pokemmo client , i tried clicking to the .SH file but nothing happend , im just so confused , would appreciate your feedback

**Comment by marc0x1** [comment]
You need to download it first.
[Releases](https://github.com/marc0x1/pokemmo-flatpak-manifest/releases/
)
